### PR TITLE
Upgrade to terraform 0.12

### PR DESCRIPTION
**Pull request by eana**
Hello there!

I hope PRs are welcomed :)

Currently, the Terraform code is written using version 0.11 and is therefore not compatible with newer versions of Terraform. This PR refactors the code to work with 0.12.

### CODE REVIEW

**Comment by isaaguilar** [comment]
Hi @eana, PRs are welcome! I haven't yet migrated to v0.12 yet, but I will review this very soon.

**Comment by eana** [comment]
@isaaguilar Is there anything I can do to get this moved forward? Thanks!

**Review by isaaguilar — APPROVED** [review]

**Comment by isaaguilar** [comment]
Thanks @eana looks good. Had to find some time to catch up on v0.12 since we're still not using where I work.

**Comment by eana** [comment]
@isaaguilar Thank you for reviewing and merging the PR.

**Pull request merged**
